### ISSUE TITLE
Remove the word "app" in the titles

### ISSUE THREAD

**Issue by prasanth-reddy-wavemaker-com** [wavemaker/showcase-apps#1]
![image](https://user-images.githubusercontent.com/57487155/78528910-2129af80-77fe-11ea-82a6-3ff6826f8b83.png)

Just say
WaveMaker Showcase

No need to say
WaveMaker Showcase App

**Comment by shahatWM** [comment]
Abhilash, please remove the word App from all titles, that represents Showcase Apps. For instance the above screenshots and relevant places. See that it will not be in all places.

**Comment by AbhiWM** [comment]
replaced 'Wavemaker Showcase App' with 'Wavemaker Showcase' throughout website and updated.

**Comment by shahatWM** [comment]
Removed the occurrence of App after Showcase, in the website.
